pipeline:
  name: build_pipeline
  identifier: build_pipeline
  tags: {}
  template:
    templateRef: reconsiletest
    versionLabel: v1
    gitBranch: main
    templateInputs:
      properties:
        ci:
          codebase:
            build: <+input>
      stages:
        - stage:
            identifier: testdeploy
            type: Deployment
            spec:
              service:
                serviceInputs:
                  serviceDefinition:
                    type: Kubernetes
                    spec:
                      variables:
                        - name: rolloutsvcvar
                          type: String
                          value: <+input>
              execution:
                steps:
                  - step:
                      identifier: testtemplate
                      template:
                        templateInputs:
                          type: Container
                          spec:
                            envVariables:
                              SCHEMA_REGISTRY_URL: <+input>.allowedValues(test, testone)
  projectIdentifier: Manisha
  orgIdentifier: default
