pipeline:
  name: new-pipeline
  identifier: newpipeline
  projectIdentifier: Manisha
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: stage-one
        identifier: stageone
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo "hey"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
