pipeline:
  name: secrets-testing
  identifier: secretstesting
  projectIdentifier: Manisha
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: secrets
        identifier: secrets
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: |+
                          echo "<+secrets.getValue('org.test-manisha')>" | base64
                          echo "<+secrets.getValue('account.test-manisha')>" | base64

                    environmentVariables: []
                    outputVariables:
                      - name: seca
                        type: String
                        value: a
                      - name: secb
                        type: String
                        value: b
                  timeout: 10m
              - step:
                  type: ShellScript
                  name: ShellScript_2
                  identifier: ShellScript_2
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: |


                          # Set the Webhook URL for the EQA pipeline
                          WEBHOOK_URL="https://app.harness.io/gateway/pipeline/api/webhook/custom/HdlSMLPUSJGzdwusTuWAlg/v3?accountIdentifier=qmrzY7joS9SsdtHPFP8WHQ&orgIdentifier=default&projectIdentifier=Manisha&pipelineIdentifier=pipeline_trigger&triggerIdentifier=testtrigger"
                          echo "Triggering EQA pipeline..."
                          response=$(curl -X POST "$WEBHOOK_URL")

                          # Print the response from the webhook
                          echo "Webhook response: $response"

                          # Extract the apiUrl from the response using jq
                          apiUrl=$(echo "$response" | jq -r '.data.apiUrl')

                          # Check if apiUrl was successfully extracted
                          if [ -z "$apiUrl" ]; then
                            echo "apiUrl not found in the response."
                            exit 1
                          fi

                          # Make a GET request to the apiUrl
                          echo "Making GET request to apiUrl: $apiUrl"
                          apiResponse=$(curl -X GET "$apiUrl")

                          # Print the GET request response
                          echo "API response: $apiResponse"
                          # Check if the trigger was successful (you can modify this based on your webhook's response)
                          #if [[ $response == *"SUCCESS"* ]]; then
                          #  echo "EQA pipeline triggered successfully."
                          #else
                          #  echo "Failed to trigger EQA pipeline. Response: $response"
                          #  exit 1
                          #fi
                          ############################################################################
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
  notificationRules:
    - name: test-notif
      identifier: testnotif
      pipelineEvents:
        - type: PipelineSuccess
      notificationMethod:
        type: Webhook
        spec:
          webhookUrl: https://app.harness.io/gateway/pipeline/api/webhook/custom/HdlSMLPUSJGzdwusTuWAlg/v3?accountIdentifier=qmrzY7joS9SsdtHPFP8WHQ&orgIdentifier=default&projectIdentifier=Manisha&pipelineIdentifier=pipeline_trigger&triggerIdentifier=testtrigger
      enabled: true
