pipeline:
  name: test-pipe-gitx
  identifier: testpipegitx
  projectIdentifier: Manisha
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: hi
        identifier: hi
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo "hi"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
