site_name: 'Example Documentation'
repo_url: https://github.com/mehar221/harness-docs
edit_uri: https://github.com/mehar221/harness-docs/blob/main/docs/README.md

nav:
  - Home: README.md

plugins:
  - techdocs-core
