apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-service
  description: A valid service
  annotations:
    backstage.io/techdocs-ref: value
  tags:
    - java
spec:
  type: service
  lifecycle: production
  owner: team-a
