{
  "replicaCount": 2,
  "image": {
    "repository": "myregistry/myapp",
    "tag": "1.0.0",
    "pullPolicy": "IfNotPresent"
  },
  "service": {
    "type": "ClusterIP",
    "port": 80
  },
  "ingress": {
    "enabled": true,
    "className": "nginx",
    "hosts": [
      {
        "host": "myapp.example.com",
        "paths": [
          {
            "path": "/",
            "pathType": "Prefix"
          }
        ]
      }
    ],
    "tls": [
      {
        "hosts": ["myapp.example.com"],
        "secretName": "myapp-tls"
      }
    ]
  },
  "resources": {
    "limits": {
      "cpu": "500m",
      "memory": "256Mi"
    },
    "requests": {
      "cpu": "250m",
      "memory": "128Mi"
    }
  },
  "env": {
    "ENVIRONMENT": "production",
    "LOG_LEVEL": "info"
  }
}
