service: simple-website
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x

functions:
  function1:
    handler: index.handler

package:
  artifact: /Users/abhinavhinger/files/handler1.zip