service: {{.Values.stack}}

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}

custom:
  stackName: ${self:service}-${self:provider.stage}

package:
  individually: true
  patterns:
    - '!**/*'
    - 'handler.js'

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: {{.Values.getpath}}
          method: get
          cors: true

resources:
  Outputs:
    StackName:
      Value: ${self:custom.stackName}
    ApiGatewayUrl:
      Value:
        Fn::Join:
          - ""
          - - "https://"
            - Ref: ApiGatewayRestApi
            - ".execute-api.${self:provider.region}.amazonaws.com/${self:provider.stage}"
    HelloFunctionUrl:
      Value:
        Fn::Join:
          - ""
          - - "https://"
            - Ref: ApiGatewayRestApi
            - ".execute-api.${self:provider.region}.amazonaws.com/${self:provider.stage}/hello"