service: my-serverless-project

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}

custom:
  stackName: ${self:service}-${self:provider.stage}

package:
  individually: true
  patterns:
    - '!**/*'
    - 'handler.js'

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get

resources:
  Outputs:
    StackName:
      Value: ${self:custom.stackName}