apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-sample-service
  description: My Sample service.
  tags: my-sample
  links:
    - title: Website
      url: https://www.apple.com/
  annotations:
    github.com/project-slug: mehar221/harness-docs
    backstage.io/techdocs-ref: dir:../../
spec:
  type: Service
  owner: my-sample-team
  lifecycle: experimental
  system: my-sample-system
