apiVersion: harness.io/v1
kind: Workflow
name: pipeline
identifier: pipeline
type: pipeline
owner: user:account/manisha.choudhary@harness.io
scope: PROJECT
projectIdentifier: Manisha
project_name: Manisha
orgIdentifier: default
org_name: default
metadata:
  description: ""
  tags:
    - test
spec:
  parameters:
    - title: Service Details
      required:
        - service_name
      properties:
        token:
          title: Harness Token
          type: string
          ui:widget: password
          ui:field: HarnessAuthToken
        service_name:
          title: Service Name
          type: string
          description: Mention the project name
  steps:
    - id: trigger
      name: Creating your appication
      action: trigger:harness-custom-pipeline
      input:
        url:
          - Harness Pipeline URL
        inputset:
          service_name: ${{ parameters.service_name }}
        apikey: ${{ parameters.token }}
  output:
    links:
      - title: Pipeline Details
        url: ${{ steps.trigger.output.PipelineUrl }}
  lifecycle: prod
