app:
  name: my-app
  namespace: default
  replicas: 3
  port: 8080

image:
  repository: library/nginx
  tag: "latest"


resources:
  requests:
    memory: "256Mi"
    cpu: "0.5"
  limits:
    memory: "512Mi"
    cpu: "1"

strategy:
  maxSurge: 1
  maxUnavailable: 0

probes:
  liveness:
    path: /healthz
    initialDelaySeconds: 15
    periodSeconds: 10
  readiness:
    path: /readyz
    initialDelaySeconds: 10
    periodSeconds: 5

service:
  type: ClusterIP
  port: 80
